chore: implement automated release workflow - part 2

diff --git a/.github/workflows/create-release.yml b/.github/workflows/create-release.yml
--- a/.github/workflows/create-release.yml
+++ b/.github/workflows/create-release.yml
@@ -13,7 +13,7 @@ on:
   workflow_dispatch:
     inputs:
       name: # release tag
-        description: 'Create release'
+        description: 'Release tag (i.e. x.y.z)'
         default: ""
         required: true
       sec-scanners-config:
@@ -130,3 +130,161 @@ jobs:
     name: Unit tests
     needs: validate-release
     uses: kyma-project/eventing-tools/.github/workflows/unit-test-reusable.yml@main
+
+  create-draft:
+    name: Create draft release
+    needs: [ bump-sec-scanners-config, validate-release ]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
+
+      - name: Create draft release
+        id: create-draft
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          REPOSITORY: ${{ github.repository_owner }}/kyma-metrics-collector
+        run: |
+          RELEASE_ID=$(./hack/scripts/create_draft_release.sh ${{ github.event.inputs.name }})
+          echo "release_id=$RELEASE_ID" >> $GITHUB_OUTPUT
+
+      - name: Create lightweight tag
+        run: |
+          git tag ${{ github.event.inputs.name }}
+          git push origin ${{ github.event.inputs.name }}
+
+    outputs:
+      release_id: ${{ steps.create-draft.outputs.release_id }}
+
+  wait-for-prow-jobs:
+    name: Wait for prow jobs
+    needs: [ create-draft, bump-sec-scanners-config ]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Wait for release-kyma-metrics-collector-build status
+        uses: autotelic/action-wait-for-status-check@6556cf50c8fb6608412945382eae73581f56cbb4
+        id: wait-for-post-kmc-release-build
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          statusName: "release-kyma-metrics-collector-build"
+          timeoutSeconds: "600"
+          ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
+
+      - name: Check if release-kyma-metrics-collector-build status is not success
+        if: steps.wait-for-post-kmc-release-build.outputs.state != 'success'
+        run: |
+          echo 'release-kyma-metrics-collector-buildfailed.'
+          exit 1
+
+  bump-kmc-chart:
+    name: Bump KMC chart
+    needs: [ bump-sec-scanners-config, wait-for-prow-jobs ]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ needs.bump-sec-scanners-config.outputs.latest_commit}}
+      - run: |
+          git checkout main
+          git pull
+
+      - name: Bump KMC chart
+        run: ./hack/scripts/bump_kmc_chart.sh ${{ inputs.name }}
+
+      - name: Create PR if anything changed
+        env:
+          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
+        run: |
+          prs=$(gh pr list -A ${{ env.GIT_NAME }} --state open --json headRefName | jq -r '.[] | .headRefName')
+          if echo $prs | tr " " '\n' | grep -F -q -x ${{ env.BUMP_KMC_BRANCH_NAME }}; then
+            echo "PR already exists, no need to create a new one"
+            echo "PR_NUMBER=$(gh pr list --search "base:main head:${{ env.BUMP_KMC_BRANCH_NAME }}" --json number | jq -r '.[] | .number')" >> $GITHUB_ENV
+          elif [ -z "$(git status --porcelain)" ]; then
+            echo "Nothing changed, no need to create PR"
+            echo "PR_NUMBER=-1" >> $GITHUB_ENV
+          else
+            PR_STATUS=$(./hack/create_bump_kmc_chart_pr.sh ${{ inputs.name }})
+            echo "PR_NUMBER=$(echo "$PR_STATUS" | tail -n 1)" >> $GITHUB_ENV
+          fi
+
+      - name: Await PR merge
+        timeout-minutes: 45
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if [ "$PR_NUMBER" -gt 0 ]; then
+            ./hack/await_pr_merge.sh
+          else
+            echo "Step skipped"
+          fi
+
+      - name: Save latest commit ref
+        id: pull-ref
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git checkout main
+          git stash
+          git pull
+          LATEST_COMMIT=$(git rev-parse HEAD)
+          echo "latest_commit=$LATEST_COMMIT" >> $GITHUB_OUTPUT
+          echo "Latest commit ref $LATEST_COMMIT"
+
+    outputs:
+      latest_commit: ${{ steps.pull-ref.outputs.latest_commit }}
+
+  publish-release:
+    name: Publish release
+    needs: [ create-draft, run-unit-tests, bump-kmc-chart ]
+    if: ${{ !inputs.dry-run }}
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          ref: ${{ needs.bump-kmc-chart.outputs.latest_commit}}
+      - run: |
+          git checkout main
+          git pull
+
+      - name: Package KMC chart
+        run: |
+          OUTPUT=$(helm package ./resources/kyma-metrics-collector -d ./)
+          FILENAME=$(echo $OUTPUT | grep -o '[^ ]*.tgz')
+          echo "KMC_CHART=$FILENAME" >> $GITHUB_ENV
+
+      - name: Upload packaged KMC chart to release
+        env:
+          BOT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: ./hack/scripts/upload_assets.sh ${{ needs.create-draft.outputs.release_id }} $KMC_CHART
+
+#It will be enabled after initial release.
+#      - name: Update KMC chart metadata
+#        run: |
+#          git checkout gh-pages
+#          helm repo index --url https://github.com/kyma-project/kyma-metrics-collector/releases/download/${{ inputs.name }} --merge ./index.yaml ./
+
+#      - name: Commit KMC chart metadata to gh-pages branch
+#        run: |
+#          git config --global user.email ${{ env.GIT_EMAIL }}
+#          git config --global user.name ${{ env.GIT_NAME }}
+#          git add index.yaml
+#          git commit -m "Update KMC chart metadata with version ${{ inputs.name }}"
+#          git push origin gh-pages
+#
+#      - name: Publish release
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        run: |
+#          git checkout main
+#          ./hack/scripts/publish_release.sh ${{ needs.create-draft.outputs.release_id }}
