fix

diff --git a/.github/workflows/pr-github-checks.yml b/.github/workflows/pr-github-checks.yml
--- a/.github/workflows/pr-github-checks.yml
+++ b/.github/workflows/pr-github-checks.yml
@@ -23,7 +23,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^area/' || (echo "area label missing"; exit 1)
+          grep -q '^area\/' || (echo "area label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
@@ -31,7 +31,7 @@ jobs:
         if: always()
         run: |
           gh api --jq '.labels.[].name' /repos/${{ github.repository }}/pulls/${{ github.event.number }} | \
-          grep -q '^kind/' || (echo "kind label missing"; exit 1)
+          grep -q '^kind\/' || (echo "kind label missing"; exit 1)
         env:
           GH_TOKEN: ${{ github.token }}
 
